### ISSUE TITLE
maintain: French

### ISSUE THREAD

**Issue by TapwaveZodiac** [revoltchat/translations#234]
### What language do you want to maintain?

French

### Link to Weblate profile

https://weblate.insrt.uk/user/bunray/

### Revolt ID

01H2XXFQ9GMW920PPWKFAXWR4G

**Comment by TapwaveZodiac** [comment]
In regards to credentials:

I am an English teacher in France and have several years of experience. I also translated every single DOOM and Build engine game to French for the GZDoom and Raze projects, more info there: https://forum.zdoom.org/viewtopic.php?t=63737

**Comment by TapwaveZodiac** [comment]
> 

I made this request specifically because I am unable to perform any reviews or contributions whatsoever, all inputs are locked out on my Weblate, making me unable to add, correct, or comment on anything. I simply followed the procedure on the Github to request access since there did not seem to be another way to do so, or the page was misleading in some way.

In this case is it possible to make it possible for me to contribute to the translation? Is there some sort of role or access that needs to be granted for this to be possible?

**Comment by Rexogamer** [comment]
Weblate seems to be a bit bugged - I accidentally set it to Restricted but can't set it back to Public. I have, however, granted you the Translator role - I'll leave this open for a bit

**Comment by Hades785** [comment]
> I would nonetheless appreciate you contributing to the French translation of Revolt, be it by reviewing existing strings that haven't been verified by me yet or by translating new strings as they come.

Welp, you sure contributed a lot.

> Whilst I don't want to hold doubts over your ability to provide good quality translation from English to French, you sadly have no contribution to the existing translation of Revolt. Because of this I cannot accept your request for maintaining the French translation which would also grant you a translator badge over no work done, thus being unfair to other people who earned the translator badge with their contributions to the project.

You've done a good bunch of nice contributions, going over stuff I had missed in verified and non-verified strings alike. And you've done a good work with rewording strings that, for some of them, I struggled to find something to put there in the first place. 
You definitely deserve the translator badge now, but as for the maintainer role that's gonna be up to you. And if you're okay with that role, I'll have to ask the other French maintainer that I approved of to see if they approve as well. At the very least I would definitely approve of it now, given that your translations are of a high quality.

Maintainers mark strings as verified if they are judged to be of good enough quality, making other people have to suggest changes rather than being able to directly edit them. We also judge other people's contributions to decide whether or not they are deserving of a translator badge (point being to not reward people who use machine translation to make a lot of low quality contributions). But as a maintainer I also tend to leave new strings untranslated for a while to let other people get a shot at them, and I pass behind them to review the string, correcting it if it has small mistakes or marking it for edit if I think it's too bad. It's not like we *have* to let other people contribute, but I like to try to get people involved on the project, even though they usually don't end up staying too long.

**Comment by TapwaveZodiac** [comment]
I'm very thankful for the feedback! Considering a sizeable amount of strings are not verified yet, I'd be happy to maintain the main French translation to speed up the process and double-check contributions by new translators.

As for middle French, since I do not have a background in Middle French linguistics, I cannot attest that my translation is accurate, but it should be stylistically appropriate and readable, so I hope we'll find a maintainer with a proper background for it who'll be able to check if what I provided for that translation is historically accurate.

**Comment by Hades785** [comment]
Alright then, @Kasahe what do you think about it?

**Comment by Kasahe** [comment]
I approve the role of contributor/translator, I've modified some of your suggestions like the "Tag", but I'm still confused about your role as maintainer.

**Comment by TapwaveZodiac** [comment]
> I approve the role of contributor/translator, I've modified some of your suggestions like the "Tag", but I'm still confused about your role as maintainer.

How would it be confusing? I'm not sure what input I can give to help there. I have a substantial amount of free time and I'd be happy to review existing strings, fixing typos and such.

**Comment by TapwaveZodiac** [comment]
Okay, I'll take the L and move on from this, then. I won't accept a role of maintainer for Middle French, I'm using resources but I am not a specialist, this is mostly filling in until an expert joins us. 

At this point I'm just hearing the same unsubstantiated feedback about "overly **formal**" (sustained is not the appropriate term, and the fact I'm having fingers pointed at me while inaccurate translations like this keep showing up, as well as regular errors both in French and in English) is making me feel like my work is simply not appreciated and that people want to keep me away from the maintenance position, especially when translators with far more mistakes are left completely uncommented on and even validated.

I'm wholly uninterested working with a team that is going to be antagonistic towards me. I'll simply @Rexogamer for a badge and focus on making contributions when necessary, though my faith in this is rather slim now.

**Comment by Rexogamer** [comment]
Done in 7e6e45906c9db57c28f1af67d1c9d0cca0357fa7.
