### ISSUE TITLE
maintain: French

### ISSUE THREAD

**Issue by Achlys12** [revoltchat/translations#246]
### What language do you want to maintain?

French

### Link to Weblate profile

https://weblate.insrt.uk/user/Achlys/

### Revolt ID

01H1P7PFR9XJSEHX03JA5BQDA9

**Comment by Achlys12** [comment]
Je pense pouvoir être un bon candidat pour ce rôle, je ne compte m’arrêter juste après avoir obtenu des rôles importants mais plutôt pouvoir aider au maximum revolt dans la traduction de la langue française, après je suis prêt a avoir vos avis pour cela

**Comment by Achlys12** [comment]
@Hades785 @Kasahe @Rexogamer sorry to ping you, I just wanted to remind you that this request is still active

**Comment by Kasahe** [comment]
Personally, I approve it because I've seen some very good suggestions and there have been very few mistakes.

**Comment by Hades785** [comment]
Went over your Weblate history to be thorough:

- Android component: Small changes to correct mistakes from someone else, good job overall (most contributions are current translations)
- Glossary component: I don't take it into consideration at all unless one spams it with machine translated stuff, so you're fine there since you didn't
- Web App component: apart from the `app.main.channel.misc.sent_file` and `app.main.channel.misc.sent_multiple_files` strings on which I built upon your suggestions (that didn't fit right with each other, one with verb at infinitive and the other using past participle) to get the current translation, and the `app.main.channel.system.channel_renamed`string on which the change you suggested was wrong and had double spaces, the rest was fine enough. Just didn't accept some of the suggestions because they didn't feel right. Also the suggestion on `app.settings.pages.appearance.mono_font` was good because although it replaces a word that is used in the font jargon, it puts a word that is more understandable in its stead I suppose. (although to me it still feels a bit off, but more accessible nonetheless).

Not counting glossary contributions, you don't have a lot of contributions, and I am a bit worried about the web app suggestions that were somewhat wrong.

Also, now that we have the AutoMod translation project, I see that you put two suggestions down on it, with each having one space character that shouldn't be there, but apart from that they were good and with the erroneous spaces removed they are the current translation and feel right.

For now I'm still a bit worried about the contributions with space errors and such, but I don't think they are done maliciously. @Kasahe is fine with you as maintainer so I'll trust their judgement.
I'll only ask that you double check your input field before sending futre contributions to make sure you didn't add double spaces or a space at the end or such.

**Comment by Kasahe** [comment]
I agree with Hades, the only thing is that if Achlys gets the role of maintainers we'll know 4 maintainers, given that Bunray has been accepted and I think a limit wouldn't be out of place because we're really active and more maintainers would be pointless.

**Comment by TapwaveZodiac** [comment]
> I agree with Hades, the only thing is that if Achlys gets the role of maintainers we'll know 4 maintainers, given that Bunray has been accepted and I think a limit wouldn't be out of place because we're really active and more maintainers would be pointless.

You stated the opposite in my thread. As I am not a maintainer, I have no input on this.

**Comment by Achlys12** [comment]
thank you for your opinion, I hope you will keep me informed @Hades785 @Kasahe

**Comment by Achlys12** [comment]
up ?

**Comment by Rexogamer** [comment]
I'll make the two of you maintainers but I think we can set a limit after that

**Comment by Achlys12** [comment]
thanks you

**Comment by Rexogamer** [comment]
Done in b68ad6810deda1f2e8e151b2f353c4f303c28b2f.
