### ISSUE TITLE
maintain: <Francais>

### ISSUE THREAD

**Issue by rymko** [revoltchat/translations#249]
### What language do you want to maintain?

Francais

### Link to Weblate profile

https://weblate.insrt.uk/user/Rymko/

### Revolt ID

01GVT7QG1VMXK9C4NQZE9THHWX

**Comment by Hades785** [comment]
Hello,

You have two contributions on the French language, both suggestions, both of which having errors. I can't accept your request for maintaining the French translation based on that…
But I am very curious about the previous activity on your Weblate account… Weblate only shows you having contributed to French, but when looking at the contribution history there are hundreds of contributions from three months ago distributed on Urdu, Latin, and Klingon languages… I must say I'm very intrigued by that.

Anyway, I'm rejecting your request for maintaining French based on the previous point.
Have a nice day.

PS: Also, you already have a maintainer request open for Latin, suggesting erroneous translations to other languages and asking to maintain them just after only makes it look like you want something out of it rather than to seriously contribute, at least that's how I see it.
