### ISSUE TITLE
badge: Russian for blank

### ISSUE THREAD

**Issue by bl4nkkk1** [revoltchat/translations#258]
### What language(s) did you translate?

Russian

### What is your Revolt ID?

01H79XWHEZQNSFJ6XSQZ0C3SDZ

### Link to Weblate profile

https://translate.revolt.chat/user/blank/

### Validations

- [X] The language has a maintainer (see the full list [here](https://github.com/revoltchat/translations#languages)).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Rexogamer** [comment]
cc @div2005

**Comment by div2005** [comment]
Hello 👋 
I've seen your suggestions, but they're all for project that is temporarily closed for contributions.

What I can say: 
- "This user hasn't set a bio yet." definitely can't be translated as "Этот пользователь еще не создал биографию.". It doesn't means "creating a bio", it's about setting/editing some information. 
- There are some moments with system messages where it doesn't match with other translation style, like instead of "описание изменилось" would be better to use another form: "описание изменено" and etc. 

So, I'd like to see more contributions from you

**Comment by Rexogamer** [comment]
Rejecting for now - feel free to re-apply if you make more contributions. Thanks!
