### ISSUE TITLE
maintain: Arabic

### ISSUE THREAD

**Issue by vloddot** [revoltchat/translations#271]
### What language do you want to maintain?

Arabic

### Link to Weblate profile

https://translate.revolt.chat/user/vloddot/

### Revolt ID

01H1RXBRZ7JBCAPHZ1RA5CRCG2

**Comment by Rexogamer** [comment]
cc @LedaThemis

**Comment by LedaThemis** [comment]
Thanks for the mention!

To begin, thank your for all your contributions @vloddot!

Upon reviewing your contributions, I've noticed that most of your contributions were relating to diacritics of the Arabic language. While this demonstrates your attention to detail and linguistic knowledge, it does not give me a clear idea on the quality of your translations.

I've also noticed that you have suggested and then removed many of your own suggestions which means that you care about the quality of the translations. (And that's commendable!)

It's worth mentioning that I've accepted many of your translations from approximately two weeks ago.

But I'm afraid that in order to make a decision, I would need to see more of your translations.

(One thing that caught my attention was your choice to translate "Webhooks" as "ربط الخدمات", care to elaborate? We can discuss this on Revolt if you're interested)

**Comment by vloddot** [comment]
Sure. Here is my username and discriminator: vloddot#2349

**Comment by LedaThemis** [comment]
After discussing it on Revolt and reviewing suggestions made over the last month, along with the enthusiasm that they've shown, I'd absolutely love to have @vloddot as a co-maintainer for the Arabic language!  Welcome! :tada: 

@Rexogamer Friendly ping to approve
