### ISSUE TITLE
maintain: Spanish

### ISSUE THREAD

**Issue by DevArxify** [revoltchat/translations#281]
### What language do you want to maintain?

Spanish

### Link to Weblate profile

https://translate.revolt.chat/user/arxify/

### Revolt ID

01FNS96STXZPRREQDW6Y7MTWZ7

**Comment by DevArxify** [comment]
I was the person to finish the Spanish translations 😎

**Comment by gatomod** [comment]
Hi again @DevArxify. We already have enough maintainers, but it's true that Atzu is no longer active.
You finished translations because they added new strings recently and I didn't have time to translate it (this month I was busy with work and studies). Anyway, thanks for your work.

For me is denied. I'll wait a response from @Rexogamer

**Comment by gatomod** [comment]
cc @fernandopal

**Comment by DevArxify** [comment]
> Hi again @DevArxify. We already have enough maintainers, but it's true that Atzu is no longer active.
> 
> You finished translations because they added new strings recently and I didn't have time to translate it (this month I was busy with work and studies). Anyway, thanks for your work.
> 
> 
> 
> For me is denied. I'll wait a response from @Rexogamer 

Understandable. I'll wait for a response from Rexo as well. Have a nice day! Viva España :)

**Comment by Rexogamer** [comment]
I'll close this one in favour of your badge request.
