### ISSUE TITLE
badge: French for RedNix

### ISSUE THREAD

**Issue by RedNight-was-taken** [revoltchat/translations#71]
### What language(s) did you translate?

French

### What is your Revolt ID?

01GAVBETYB5HP9XNYE2YHGDAF5

### Link to Weblate profile

https://weblate.insrt.uk/user/RedNix/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by Hades785** [comment]
Some of your translations were pretty subpar to be honest… Some of your edits, like "Marquer le compte ~~pour~~**comme** suppression" (`app.settings.pages.account.manage.delete`) or "Activer/Désactiver la mention de l'aut**h**eur" (`app.main.channel.reply.toggle`, although you later fixed that one), are a bit clumsy…
And others like "~~Ne plus être muet~~**Démuter**" (`app.main.channel.voice.unmute`) or your first action, suggesting the following change "~~Nom d'utilisateur~~**Pseudo**" (` login.username`, suggesting because it's one of the few strings that I had validated when I validated around 80 strings when I had some time for it), are just plainly wrong… "Démuter" is an Anglicism and should be avoided as such, at least on written French, and "pseudo" would fit for "pseudonym", and even then you'd rather translate less familiarly to "pseudonym".

But on the other hand, some of your contributions weren't too bad, fixing some typos along the way, giving better wordings to some strings… I passed behind to edit them a bit to make a blend between your contributions and the previous translation, but I appreciate this effort.

I'm just wondering whether you were doing this seriously or just going through random strings to make edits that would seem inconspicuous enough to let you get a badge for free.
I'm unsure because some edits feel lazy or just taken directly from speech habits (familiar register), whilst at the same time *you're still as of now making edits* and some are genuinely good… So yeah, I don't really know what to think, I'll just continue to go back behind your edits and validating a few more strings along the way for now.

**Comment by Hades785** [comment]
Oh and something I just noticed from your notification sounds strings edits... You didn't *seem* to be looking at string context when making your edits, please do check the context of any string you edit if you weren't doing this already.

**Comment by RedNight-was-taken** [comment]
Hi
First of all thanks for your feedback, I'm new to this translation platform
and just looked if I can fix a few things, for example "comme supression"
seems better to me than "pour supression" - but yeah its just my speech
habits I guess.

For the badge, I first did not know you can get one, I saw a translation on
the app that was weird and started translating around ~15 strings. The next
day, I saw that you can get a badge so I translated more strings and I
think focused a bit more on it.

For the string context thanks for letting me know I'll focus more on it.

**Comment by Hades785** [comment]
Alright, thanks for your contributions, honestly I wouldn't have validated the strings I did yesterday/today any time soon if not for them =w=
I need to work more on validating them, but also going through 600 hundred strings is a lot (though I knew what I was getting into), even more when you need to fix them… (I tend to use the app in English too so I don't necessarily notice the translation errors except when scrubbing Weblate…) And so I ended up procrastinating in the end x)

> for example "comme supression" seems better to me than "pour supression"

Maybe you thought of "mark _as deleted_" ("marquer _comme supprimé_") rather than "mark _for deletion_" ("marquer _pour suppression_")?

**Comment by RedNight-was-taken** [comment]
Sorry for all the reverts you have to do cause of me x)

And yeah now thinking of it I tought of "mark as deleted"

**Comment by insertish** [comment]
Just checking in on this since it went stale, should a badge be granted or no?
cc @Hades785 as maintainer

**Comment by Hades785** [comment]
I'm fine with that, their work was genuine and helped fix some issues from older translations or small mistakes from newer ones.
