### ISSUE TITLE
badge(pending): <Portuguese (Portugal)> for <Sliced>

### ISSUE THREAD

**Issue by SlicedBlueApple** [revoltchat/translations#77]
### What language(s) did you translate?

Portuguese (Portugal)

### What is your Revolt ID?

Sliced

### Link to Weblate profile

https://weblate.insrt.uk/user/Sliced/

### Validations

- [X] The language has a maintainer, [see list](https://github.com/revoltchat/translations#language-maintainers).
- [X] You agree that your translations are to a reasonable standard.

**Comment by insertish** [comment]
cc @Tmpod
Could I have you check over [quality of changes](https://weblate.insrt.uk/changes/?user=Sliced&project=&lang=pt_PT&user=Sliced&start_date=&end_date=).
I'm running under the assumption that this language is usually up-to-date so I'm not going to factor in number of translations into whether a badge is granted or not since the language is 100% right now.

**Comment by Tmpod** [comment]
> Could I have you check over quality of changes.

Yeah, those changes are all good.
My only concern is with "deafen", which was translated quite literally, and
that's not very usual for this context.  
However, I'm not 100% sure which term applies best here and is most used, so
I'll have to research it myself too.

> I'm running under the assumption that this language is usually up-to-date so

Yeah, it has been kept up-to-date, usually within 24h of new strings being
added.
